// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using serviceApiWebAdminRealestate.Api;

#nullable disable

namespace serviceApiWebAdminRealestate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("serviceApiWebAdminRealestate.Models.Domain.UserAccounts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("full_name")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.ToTable("user_account");

                    b.HasData(
                        new
                        {
                            id = 1,
                            full_name = "Administrator",
                            password = "AQAAAAIAAYagAAAAEEeGqT/HxmA0RRmUIgxYAz5+WYKOa/kSO2N+JsAGLwCRiPg8BrJU3GN1OHAldu6XNQ==",
                            username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
